#!/bin/bash
#Generates a password, substitutes this password into the word PLACEHOLDER in a given file, drops and then creates a user
USER_PASS=$(openssl rand -base64 32 | sed 's/[^a-zA-Z0-9]//g')
sed -i "s/application\.secret=\"PLACEHOLDER\"/application\.secret=\"$USER_PASS\"/" $1
